name: Update GeoJSON

on:
  schedule:
    - cron: '0 * * * *' # 毎時0分に実行
  workflow_dispatch:

jobs:
  update-geojson:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout Repository
        uses: actions/checkout@v2
        with:
          token: ${{ secrets.GITHUB_TOKEN }}

      - name: Download GeoJSON Files
        run: |
          curl -o data/mlit/before_after.geojson https://www.mlit.go.jp/road/r6noto/map/json/before_after.geojson
          curl -o data/mlit/damage_situation_aerial_photography.geojson https://www.mlit.go.jp/road/r6noto/map/json/damage_situation_aerial_photography.geojson
          curl -o data/mlit/damaged_area.geojson https://www.mlit.go.jp/road/r6noto/map/json/damaged_area.geojson
          curl -o data/mlit/recovery_point.geojson https://www.mlit.go.jp/road/r6noto/map/json/recovery_point.geojson
          curl -o data/mlit/ETC2.0_speed_data.geojson https://www.mlit.go.jp/road/r6noto/map/json/ETC2.0_speed_data.geojson
          curl -o data/mlit/emergency_restored_section.geojson https://www.mlit.go.jp/road/r6noto/map/json/emergency_restored_section.geojson
          curl -o data/mlit/sagyou.geojson https://www.mlit.go.jp/road/r6noto/map/json/sagyou.geojson
          curl -o data/mlit/img/usage_guide.png https://www.mlit.go.jp/road/r6noto/map/img/usage_guide.png

      - name: Commit and Push Changes
        run: |
          git config --global user.email "y.shiwaku.5519@gmail.com"
          git config --global user.name "shi-works"
          git add data/mlit/*.geojson
          git add data/mlit/img/usage_guide.png
          git diff --staged --quiet || (git commit -m "Update GeoJSON files and image" && git push)

