name: Update GeoJSON

on:
  schedule:
    - cron: '0 * * * *' # 毎時0分に実行
  workflow_dispatch:

jobs:
  update-geojson:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout Repository
        uses: actions/checkout@v2
        with:
          token: ${{ secrets.GITHUB_TOKEN }}

      - name: Download GeoJSON Files
        run: |
          curl -o data/hypo20240101.geojson https://www.jma.go.jp/bosai/hypo/data/2024/01/hypo20240101.geojson
          curl -o data/hypo20240102.geojson https://www.jma.go.jp/bosai/hypo/data/2024/01/hypo20240102.geojson
          curl -o data/hypo20240103.geojson https://www.jma.go.jp/bosai/hypo/data/2024/01/hypo20240103.geojson
          curl -o data/hypo20240104.geojson https://www.jma.go.jp/bosai/hypo/data/2024/01/hypo20240104.geojson
          curl -o data/hypo20240105.geojson https://www.jma.go.jp/bosai/hypo/data/2024/01/hypo20240105.geojson
          curl -o data/hypo20240106.geojson https://www.jma.go.jp/bosai/hypo/data/2024/01/hypo20240106.geojson
          curl -o data/hypo20240107.geojson https://www.jma.go.jp/bosai/hypo/data/2024/01/hypo20240107.geojson
          curl -o data/hypo20240108.geojson https://www.jma.go.jp/bosai/hypo/data/2024/01/hypo20240108.geojson
          curl -o data/hypo20240109.geojson https://www.jma.go.jp/bosai/hypo/data/2024/01/hypo20240109.geojson
          curl -o data/hypo20240110.geojson https://www.jma.go.jp/bosai/hypo/data/2024/01/hypo20240110.geojson
          curl -o data/hypo20240111.geojson https://www.jma.go.jp/bosai/hypo/data/2024/01/hypo20240111.geojson
          curl -o data/hypo20240112.geojson https://www.jma.go.jp/bosai/hypo/data/2024/01/hypo20240112.geojson
          curl -o data/hypo20240113.geojson https://www.jma.go.jp/bosai/hypo/data/2024/01/hypo20240113.geojson
          curl -o data/hypo20240114.geojson https://www.jma.go.jp/bosai/hypo/data/2024/01/hypo20240114.geojson
          curl -o data/hypo20240115.geojson https://www.jma.go.jp/bosai/hypo/data/2024/01/hypo20240115.geojson
          curl -o data/hypo20240116.geojson https://www.jma.go.jp/bosai/hypo/data/2024/01/hypo20240116.geojson
          curl -o data/hypo20240117.geojson https://www.jma.go.jp/bosai/hypo/data/2024/01/hypo20240117.geojson
          curl -o data/hypo20240118.geojson https://www.jma.go.jp/bosai/hypo/data/2024/01/hypo20240118.geojson
          curl -o data/hypo20240119.geojson https://www.jma.go.jp/bosai/hypo/data/2024/01/hypo20240119.geojson
          curl -o data/hypo20240120.geojson https://www.jma.go.jp/bosai/hypo/data/2024/01/hypo20240120.geojson
          curl -o data/hypo20240121.geojson https://www.jma.go.jp/bosai/hypo/data/2024/01/hypo20240121.geojson
          curl -o data/hypo20240122.geojson https://www.jma.go.jp/bosai/hypo/data/2024/01/hypo20240122.geojson
          curl -o data/hypo20240123.geojson https://www.jma.go.jp/bosai/hypo/data/2024/01/hypo20240123.geojson
          curl -o data/hypo20240124.geojson https://www.jma.go.jp/bosai/hypo/data/2024/01/hypo20240124.geojson
          curl -o data/hypo20240125.geojson https://www.jma.go.jp/bosai/hypo/data/2024/01/hypo20240125.geojson
          curl -o data/hypo20240126.geojson https://www.jma.go.jp/bosai/hypo/data/2024/01/hypo20240126.geojson
          curl -o data/hypo20240127.geojson https://www.jma.go.jp/bosai/hypo/data/2024/01/hypo20240127.geojson
          curl -o data/hypo20240128.geojson https://www.jma.go.jp/bosai/hypo/data/2024/01/hypo20240128.geojson
          
      - name: Commit and Push Changes
        run: |
          git config --global user.email "y.shiwaku.5519@gmail.com"
          git config --global user.name "shi-works"
          git add data/*.geojson
          git diff --staged --quiet || (git commit -m "Update GeoJSON files" && git push)

